### ISSUE TITLE
More a question than an issue , LogOdds Threshold

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [morrislab/rnascan#3]
I was wondering how to filter out the severals motifs found in the final output using the LogOdds value.
[Here](http://cisbp-rna.ccbr.utoronto.ca/TFTools.php) it seems you set 6 ... Is there a maximum value for the LogOdds , like 10 or something ?

**Comment by kcha** [comment]
Hi, there is no maximum. You can play around with the thresholds to see what works for you. For longer motifs you may want to consider using a higher threshold.
