### ISSUE TITLE
Issues with redirecting <stdout> in python3

### ISSUE THREAD

**Issue by katenie** [morrislab/rnascan#5]
Hi Kevin,
There seems to be an issue with redirecting STDOUT in python3. The following script redirects motif hits to `test_hits.tab` with no issues in python2, but in python3, it creates an empty `test_hits.tab` file, and creates and writes to a file named `<stdout>` in the directory where `rnascan` is executed.

`rnascan -p test_rnacompete_pfm.txt --bg_seq background_prob.txt test.fasta > test_hits.tab`

**Comment by kcha** [comment]
Hi Kate, thanks for sharing this. This is strange. I take a similar approach in QAPA to write to stdout and have never seen this issue before. Out of curiosity, what version of pandas are you using? I'm wondering if it is related to a pandas bug: https://github.com/pandas-dev/pandas/issues/21561

**Comment by katenie** [comment]
Hi Kevin, you are right. The issue disappeared after I updated the pandas package. Thanks for letting me know!

**Comment by kcha** [comment]
Great! Maybe I should increment the pandas version requirement to something more recent.
